---
- name: Install MySQL and prerequisites
  apt:
    pkg:
    - apt-transport-https
    - wget
- name: Add an Apt signing key, uses whichever key is at the URL
  ansible.builtin.apt_key:
    url: https://packages.grafana.com/gpg.key
    state: present
- name: Add specified repository into sources list
  ansible.builtin.apt_repository:
    repo: deb https://packages.grafana.com/oss/deb stable main
    state: present
- name: Update freshly installed system
  apt: 
    update_cache: yes 
    cache_valid_time: 3600
- name: Install MySQL and prerequisites
  apt:
    pkg:
    - grafana
